### ISSUE TITLE
Add Hacktoberfest Labels for the project 

### ISSUE THREAD

**Issue by shivaylamba** [scaleracademy/twitter-backend-java#26]
Hi @ohbus, as part of Scaler Open Source, this repository will accept hacktoberfest related contributions, so can you add the following tags to the repository : 
- hacktoberfest 
- hacktoberfest-accepted 
- hacktoberfest2021

**Comment by ohbus** [comment]
Hi @shivaylamba I have already added the `hacktoberfest` topic to the project to make it eligible for participation.

These two tags are optional `hacktoberfest-accepted`, `hacktoberfest2021` but if you insist I may add them to the repository as well.

Thank you so much for this.

**Comment by shivaylamba** [comment]
Also @ohbus is it possible to connect with you on Discord?, I sent you a message on Discord
