### ISSUE TITLE
INFRA: add dockerization support

### ISSUE THREAD

**Issue by championswimmer** [scaleracademy/twitter-backend-java#3]
allow building a docker file of this project, also add a `docker-compose.yml` file that can deploy this with a postgres instance.

**Comment by ohbus** [comment]
> allow building a docker file of this project, also add a `docker-compose.yml` file that can deploy this with a Postgres instance.

I did it using MySQL, would you want the application to be running on Postgres instead?

**Comment by championswimmer** [comment]
Sure MySQL works too :)
